version: '2'
services:
 postgres:
   image: postgres:9.6
   ports:
     - "5432:5432"
   environment:
     - POSTGRES_DB=clinica_vita
     - POSTGRES_USER=clinica
     - POSTGRES_PASSWORD=vita
     - MAX_CONNECTIONS=100
