# LOGGING
logging:
  file: target/clinica-vita.log
  level:
    org.fpu.locadora: DEBUG
    org.fpu.test.locadora: DEBUG
    org.springframework: INFO
    org.hibernate: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clinica_vita
    username: clinica
    password: vita
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

      
# LIQUIBASE
liquibase:
  enabled: true
  change-log: classpath:data/changelog/db.changelog-master.xml
  url: jdbc:postgresql://localhost:5432/clinica_vita
  user: clinica
  password: vita