# LOGGING
logging:
  file: target/clinica-vita.log
  level:
    org.fpu.locadora: DEBUG
    org.fpu.test.locadora: DEBUG
    org.springframework: INFO
    org.hibernate: INFO

# DATABASE
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/clinica_vita
    username: clinica
    password: vita
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
