package org.fpu.clinica.pessoa;

public enum TipoCidade {
		
	ABAETE("Abaete"),
	ABAETEDOSMENDES("Abaete dos Mendes"),
	ABAIBA("Abaiba"),
	ABRECAMPO("Abre Campo"),
	ABREUS("Abreus"),
	ACAIACA("Acaiaca"),
	ACUCENA("Acucena"),
	ACURUI("Acurui"),
	ADAOCOLARES("Adao Colares"),
	AGUABOA("Agua Boa"),
	AGUABRANCADEMINAS("Agua Branca de Minas"),
	AGUACOMPRIDA("Agua Comprida"),
	SAOSEBASTIAODORIOVERDE("Sao Sebastiao do Rio Verde"),
	SAOSEBASTIAODOSACRAMENTO("Sao Sebastiao do Sacramento"),
	SAOSEBASTIAODOSOBERBO("Sao Sebastiao do Soberbo"),
	SAOSEBASTIAODOSPOCOES("Sao Sebastiao dos Pocoes"),
	SAOSEBASTIAODOSROBERTOS("Sao Sebastiao dos Robertos"),
	SAOSEBASTIAODOSTORRES("Sao Sebastiao dos Torres"),
	SAOTIAGO("Sao Tiago"),
	SAOTOMASDEAQUINO("Sao Tomas de Aquino"),
	SAOTOMEDASLETRAS("Sao Tome das Letras"),
	SAOVICENTE("Sao Vicente"),
	SAOVICENTEDAESTRELA("Sao Vicente da Estrela"),
	SAOVICENTEDEMINAS("Sao Vicente de Minas"),
	SAOVICENTEDOGRAMA("Sao Vicente do Grama"),
	SAOVICENTEDORIODOCE("Sao Vicente do Rio Doce"),
	SAOVITOR("Sao Vitor"),
	SAPUCAI("Sapucai"),
	SAPUCAIMIRIM("Sapucai-mirim"),
	SAPUCAIA("Sapucaia"),
	SAPUCAIADEGUANHAES("Sapucaia de Guanhaes"),
	SAPUCAIADONORTE("Sapucaia do Norte"),
	SARANDIRA("Sarandira"),
	SARDOA("Sardoa"),
	SARZEDO("Sarzedo"),
	SAUDADE("Saudade"),
	SEMPEIXE("Sem Peixe"),
	SENADORAMARAL("Senador Amaral"),
	SENADORCORTES("Senador Cortes"),
	SENADORFIRMINO("Senador Firmino"),
	SENADORJOSEBENTO("Senador Jose Bento"),
	SENADORMELOVIANA("Senador Melo Viana"),
	SENADORMODESTINOGONCALVES("Senador Modestino Goncalves"),
	SENADORMOURAO("Senador Mourao"),
	SENHORADAGLORIA("Senhora da Gloria"),
	SENHORADAPENHA("Senhora da Penha"),
	SENHORADASDORES("Senhora das Dores"),
	SENHORADEOLIVEIRA("Senhora de Oliveira"),
	SENHORADOCARMO("Senhora do Carmo"),
	SENHORADOPORTO("Senhora do Porto"),
	SENHORADOSREMEDIOS("Senhora dos Remedios"),
	SERENO("Sereno"),
	SERICITA("Sericita"),
	SERITINGA("Seritinga"),
	SERRAAZUL("Serra Azul"),
	SERRAAZULDEMINAS("Serra Azul de Minas"),
	SERRABONITA("Serra Bonita"),
	SERRADACANASTRA("Serra da Canastra"),
	SERRADASAUDADE("Serra da Saudade"),
	SERRADASARARAS("Serra das Araras"),
	SERRADOCAMAPUA("Serra do Camapua"),
	SERRADOSALITRE("Serra do Salitre"),
	SERRADOSAIMORES("Serra dos Aimores"),
	SERRADOSLEMES("Serra dos Lemes"),
	SERRANOVA("Serra Nova"),
	SERRANIA("Serrania"),
	SERRANOPOLISDEMINAS("Serranopolis de Minas"),
	SERRANOS("Serranos"),
	SERRO("Serro"),
	SERTAOZINHO("Sertaozinho"),
	SETECACHOEIRAS("Sete Cachoeiras"),
	SETELAGOAS("Sete Lagoas"),
	SETUBINHA("Setubinha"),
	SILVACAMPOS("Silva Campos"),
	SILVAXAVIER("Silva Xavier"),
	SILVANO("Silvano"),
	SILVEIRACARVALHO("Silveira Carvalho"),
	SILVEIRANIA("Silveirania"),
	SILVESTRE("Silvestre"),
	SILVIANOPOLIS("Silvianopolis"),
	SIMAOCAMPOS("Simao Campos"),
	SIMAOPEREIRA("Simao Pereira"),
	SIMONESIA("Simonesia"),
	SOBRALPINTO("Sobral Pinto"),
	SOBRALIA("Sobralia"),
	SOLEDADEDEMINAS("Soledade de Minas"),
	SOPA("Sopa"),
	TABAJARA("Tabajara"),
	TABAUNA("Tabauna"),
	TABUAO("Tabuao"),
	TABULEIRO("Tabuleiro"),
	TAIOBEIRAS("Taiobeiras"),
	TAPARUBA("Taparuba"),
	TAPIRA("Tapira"),
	TAPIRAI("Tapirai"),
	TAPUIRAMA("Tapuirama"),
	TAQUARACUDEMINAS("Taquaracu de Minas"),
	TARUACU("Taruacu"),
	TARUMIRIM("Tarumirim"),
	TEBAS("Tebas"),
	TEIXEIRAS("Teixeiras"),
	TEJUCO("Tejuco"),
	TEOFILOOTONI("Teofilo Otoni"),
	TERRABRANCA("Terra Branca"),
	TIMOTEO("Timoteo"),
	TIRADENTES("Tiradentes"),
	TIROS("Tiros"),
	TOBATI("Tobati"),
	TOCANDIRA("Tocandira"),
	TOCANTINS("Tocantins"),
	TOCOSDOMOJI("Tocos do Moji"),
	TOLEDO("Toledo"),
	TOMASGONZAGA("Tomas Gonzaga"),
	TOMBOS("Tombos"),
	TOPAZIO("Topazio"),
	TORNEIROS("Torneiros"),
	TORREOES("Torreoes"),
	TRESCORACOES("Tres Coracoes"),
	TRESILHAS("Tres Ilhas"),
	TRESMARIAS("Tres Marias"),
	TRESPONTAS("Tres Pontas"),
	TRIMONTE("Trimonte"),
	TUIUTINGA("Tuiutinga"),
	TUMIRITINGA("Tumiritinga"),
	TUPACIGUARA("Tupaciguara"),
	TUPARECE("Tuparece"),
	TURMALINA("Turmalina"),
	TURVOLANDIA("Turvolandia"),
	UBA("Uba"),
	UBAI("Ubai"),
	UBAPORANGA("Ubaporanga"),
	UBARI("Ubari"),
	UBERABA("Uberaba"),
	UBERLANDIA("Uberlandia"),
	UMBURATIBA("Umburatiba"),
	UMBUZEIRO("Umbuzeiro"),
	UNAI("Unai"),
	UNIAODEMINAS("Uniao de Minas"),
	URUANADEMINAS("Uruana de Minas"),
	URUCANIA("Urucania"),
	URUCUIA("Urucuia"),
	USINAMONTEALEGRE("Usina Monte Alegre"),
	VAIVOLTA("Vai-volta"),
	VALADARES("Valadares"),
	VALAO("Valao"),
	VALEVERDEDEMINAS("Vale Verde de Minas"),
	VALOFUNDO("Valo Fundo"),
	VARGEMALEGRE("Vargem Alegre"),
	VARGEMBONITA("Vargem Bonita"),
	VARGEMGRANDEDORIOPARDO("Vargem Grande do Rio Pardo"),
	VARGEMLINDA("Vargem Linda"),
	VARGINHA("Varginha"),
	VARJAODEMINAS("Varjao de Minas"),
	VARZEADAPALMA("Varzea da Palma"),
	VARZELANDIA("Varzelandia"),
	VAUACU("Vau-acu"),
	VAZANTE("Vazante"),
	VERACRUZDEMINAS("Vera Cruz de Minas"),
	VERDELANDIA("Verdelandia"),
	VEREDADOPARAISO("Vereda do Paraiso"),
	VEREDAS("Veredas"),
	VEREDINHA("Veredinha"),
	VERISSIMO("Verissimo"),
	VERMELHO("Vermelho"),
	VERMELHONOVO("Vermelho Novo"),
	VERMELHOVELHO("Vermelho Velho"),
	VESPASIANO("Vespasiano"),
	VICOSA("Vicosa"),
	VIEIRAS("Vieiras"),
	VILABOMJESUS("Vila Bom Jesus"),
	VILACOSTINA("Vila Costina"),
	VILANOVADEMINAS("Vila Nova de Minas"),
	VILANOVADOSPOCOES("Vila Nova dos Pocoes"),
	VILAPEREIRA("Vila Pereira"),
	VILASBOAS("Vilas Boas"),
	VIRGEMDALAPA("Virgem da Lapa"),
	VIRGINIA("Virginia"),
	VIRGINOPOLIS("Virginopolis"),
	VIRGOLANDIA("Virgolandia"),
	VISCONDEDORIOBRANCO("Visconde do Rio Branco"),
	VISTAALEGRE("Vista Alegre"),
	VITORINOS("Vitorinos"),
	VOLTAGRANDE("Volta Grande"),
	WENCESLAUBRAZ("Wenceslau Braz");

	

	private String descricao;
	
	TipoCidade(String descricao){
		this.descricao = descricao;
	}
	
	public String getDescricao(){
		return descricao;
	}
}
